// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIEQ8a_Dwte1muVOZc44O5Do9Cge7HMqo',
    appId: '1:847710015802:web:5e9199c6fb9d8c3bbcc003',
    messagingSenderId: '847710015802',
    projectId: 'studybuddyiamd',
    authDomain: 'studybuddyiamd.firebaseapp.com',
    storageBucket: 'studybuddyiamd.firebasestorage.app',
    measurementId: 'G-8NPRGDMKFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcGSwX6HikbuEVg5d2ztSlmLebGGoxq1A',
    appId: '1:847710015802:android:c591d9828d85c811bcc003',
    messagingSenderId: '847710015802',
    projectId: 'studybuddyiamd',
    storageBucket: 'studybuddyiamd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDrn-_SXnDN4yn7XiLNJ-_-z1BMgVRrM',
    appId: '1:847710015802:ios:c18ebd63c3f38567bcc003',
    messagingSenderId: '847710015802',
    projectId: 'studybuddyiamd',
    storageBucket: 'studybuddyiamd.firebasestorage.app',
    iosClientId: '847710015802-bso3vpqlbqmdr3oga5najf0pb31nlgqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.studybuddyClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIEQ8a_Dwte1muVOZc44O5Do9Cge7HMqo',
    appId: '1:847710015802:web:8b561304d41d0ee7bcc003',
    messagingSenderId: '847710015802',
    projectId: 'studybuddyiamd',
    authDomain: 'studybuddyiamd.firebaseapp.com',
    storageBucket: 'studybuddyiamd.firebasestorage.app',
    measurementId: 'G-DRERL0XDZ0',
  );
}
